name: Mirror to GitLab

on:
  push:
    branches:
      - '**'
    tags:
      - '**'

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Mirror clone and push to GitLab
        env:
          GITLAB_TOKEN: ${{ secrets.SECRET_GITLAB_TOKEN }}
          GITLAB_PROJECT: bjimeno22/coastal-watch
        run: |
          git clone --mirror "https://github.com/${GITHUB_REPOSITORY}.git" repo-mirror
          cd repo-mirror
          git push --mirror "https://oauth2:${GITLAB_TOKEN}@gitlab.com/${GITLAB_PROJECT}.git"

